### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by pehsa** [OpenNFS/OpenNFS#20]
Hello,

Good project!

I don't know if you heard about these two project:

https://github.com/jeff-1amstudios/OpenNFS1
https://github.com/zaps166/NFSIISE

I think you can get ideas from them for the NFS1 and NFS2

**Comment by AmrikSadhra** [comment]
Hi! I'm aware of both projects, and will likely attempt to integrate chunks of OpenNFS1 into this project for Need for Speed 1 support. Thanks for stopping by! :)
