### ISSUE TITLE
OpenNFS.exe - System Error

### ISSUE THREAD

**Issue by ghost** [OpenNFS/OpenNFS#21]
When attempting to run these errors appear.

The code execution cannot proceed because zlib1_.dll was not found. Reinstalling the program may fix the problem.

The code execution cannot proceed because libbz2-1_.dll was not found. Reinstalling the program may fix the problem.

The code execution cannot proceed because libpng16-16_.dll was not found. Reinstalling the program may fix the problem.

**Comment by AmrikSadhra** [comment]
Temporarily make use of the MSVC build on VSTS as a work around, I seemed to have killed linking on the MinGW path (at some point, sorry!). I'll be sure to look into it tomorrow. Calling cmake generate locally with the visual studio generator will also produce a working executable.
