### ISSUE TITLE
Project Build Walkthrough

### ISSUE THREAD

**Issue by JonathanGrant92** [OpenNFS/OpenNFS#27]
RIP

**Comment by janisozaur** [comment]
Oh my, this _advice_ should not be followed by anyone.

There is exactly zero need to use superuser permissions to build projects, I hope you realize how absurd that sounds.

The configuration of the project is following established form: create a build directory, run cmake, build. Compilation in tree is ill-advised.

**Comment by JonathanGrant92** [comment]
unnecessarily provocative

**Comment by AmrikSadhra** [comment]
Hey Jonathan, really appreciate you breaking this one down. I'll try to update the README to make things clearer.

As a tip for the future, you can generally work out exactly what you need to do to build by looking at any Continuous Integration scripts; they'll detail all the steps a clean Linux/Mac/Windows box goes through to build the project (azure-pipelines.yml). Helps me out tons on new codebases! 

Thanks for the issue. Would happily merge a PR of a new README if you could clear out any sudo stuff as @janisozaur has stated.
