### ISSUE TITLE
Add support for GLES3

### ISSUE THREAD

**Issue by myself600** [OpenNFS/OpenNFS#32]
After successful compilation and populating the resource folder, I get the following error:

#### Output of OpenNFS Git a3c9280
> 11:04:47 WARNING [Renderer.h->GlfwError:49]:     GLX: Failed to create context: GLXBadFBConfig
11:04:47 WARNING [Renderer.cpp->InitOpenGL:31]:  Failed to create a GLFW window
^[
11:04:52 WARNING [Renderer.h->GlfwError:49]:     The GLFW library is not initialized
11:04:52 WARNING [Renderer.h->GlfwError:49]:     The GLFW library is not initialized
11:04:52 WARNING [Renderer.cpp->InitOpenGL:42]:  Failed to initialize GLEW
11:04:52 WARNING [Renderer.h->GlfwError:49]:     The GLFW library is not initialized
11:04:52 WARNING [Renderer.h->GlfwError:49]:     The GLFW library is not initialized

[OpenNFS.log](https://github.com/OpenNFS/OpenNFS/files/9689930/OpenNFS.log)
[OpenNFS.20221001-103448.log](https://github.com/OpenNFS/OpenNFS/files/9689932/OpenNFS.20221001-103448.log)

#### Output of OpenNFS 0.3
> 11:12:00 WARNING [Car.cpp->Car:25]:              AI Neural network couldn't be loaded from ./assets/bestRacer.net, randomising weights
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:49]: 0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:64]: 0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:81]: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:49]: 0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:64]: 0:2(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:81]: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:49]: 0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:64]: 0:2(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
...
11:12:00 WARNING [BaseShader.cpp->BaseShader:81]: error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
11:12:00 WARNING [CarShader.cpp->loadEnvMapTextureData:24]: Assertion `Utils::LoadBmpCustomAlpha(filename.str().c_str(), &data, &width, &height, 0)` failed in /home/pbpro/Stiahnuté/OpenNFS-0.3/src/Shaders/CarShader.cpp line 24: Environment map texture loading failed!

[OpenNFS-0.3.log](https://github.com/OpenNFS/OpenNFS/files/9689946/OpenNFS-0.3.log)
[OpenNFS.20221001-105052.log](https://github.com/OpenNFS/OpenNFS/files/9689948/OpenNFS.20221001-105052.log)

### System info:
Manjaro ARM 22.09
Pinebook Pro RK3399, Mali-T860 (Panfrost), Mesa 22.1.7
[glxinfo.log](https://github.com/OpenNFS/OpenNFS/files/9689951/glxinfo.log)

**Comment by myself600** [comment]
After compiling OpenXRay, I'm receiving a similar error: https://github.com/OpenXRay/xray-16/issues/594. It seems this is related to Panfrost only supporting OpenGL 3.1 atm:

> $ glxinfo | grep "OpenGL version string"
OpenGL version string: 3.1 Mesa 22.1.7

**Edit:** Mali-T860 MP4 peaks at OpenGL ES 3.2 and Vulkan 1.1 (not supported by Panfrost) via the provided binary driver, so OpenNFS can't run

**Comment by AmrikSadhra** [comment]
Yeah, that sounds spot on. You can go ahead and request a different GL context by modifying "Renderer.cpp" L23 with 
`glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);`. You'll also need to modify `ONFS_GL_VERSION `in "Config.h", as that's prepended to every GLSL file. IIRC, @janisozaur did something similar when he moved the project to GLES2 for RasPi.

**Comment by myself600** [comment]
I've tried this, but no success:

> 12:09:37 WARNING [Renderer.h->GlfwError:49]:     Context profiles are only defined for OpenGL version 3.2 and above

https://github.com/janisozaur/OpenNFS/tree/es-30-shaders only runs if I set ``ImGui_ImplOpenGL3_Init("#version 140");`` in "Renderer.cpp", and of course, with broken rendering.

**Comment by myself600** [comment]
I got it partially working,

Changing GLFW_CONTEXT_VERSION_MINOR to 0, GLFW_OPENGL_~CORE~ANY_PROFILE and ONFS_GL_VERSION to "300 es", got me to a blue screen, After backporting https://github.com/janisozaur/OpenNFS/commit/fe92778785607efeff48592f23941b9c0826f3d8, removing the offending #version lines and adding ``precision mediump float;`` to the remaining shaders...

![opennfs-gles30](https://user-images.githubusercontent.com/3542623/195421928-bc22cd5f-6ed7-40ea-9957-01fddff23c3f.gif)

It's slow and unusable.


### Attachments:

[OpenNFS-git.log](https://github.com/OpenNFS/OpenNFS/files/9767803/OpenNFS-git.log)
[OpenNFS.20221012-203023.log](https://github.com/OpenNFS/OpenNFS/files/9767804/OpenNFS.20221012-203023.log)
[patched_files.gz](https://github.com/OpenNFS/OpenNFS/files/9767886/patched_files.gz) (rename to .7z)

**Comment by janisozaur** [comment]
I did briefly try reviving gles port, but unfortunately it is too much of a hassle for me now, mostly due to the project setup and vendoring all off the libraries instead of using system ones.

I got it working in the past and I don't recall having to port any features missing from big GL, so you must be close. I think it was a bit slow, but given it was running on raspi3, that's expected - you should be getting somewhat decent performance on desktop.

**Comment by myself600** [comment]
## 1.

[CMakeLists.txt](https://github.com/OpenNFS/OpenNFS/files/9794431/CMakeLists.txt)

### Arch dependencies:
freetype2
boost
g3log
bullet
glew
glm + ``sudo sed -i 's,${PACKAGE_PREFIX_DIR},/usr,' /lib/cmake/glm/glmConfig.cmake``
glfw
https://github.com/ocornut/imgui + ``sed -i s/examples/backends/ src/Renderer/{,RaceNet}Renderer.h``
tinyobjloader


## 2.

I've tried https://github.com/janisozaur/OpenNFS/tree/es-30-shaders previously, but it behaved alike:

![opennfs-es-30-shaders](https://user-images.githubusercontent.com/3542623/196039736-4f87e21e-4214-4307-994e-0c5fd3ee2147.gif)

![opennfs-es-30-shaders_2](https://user-images.githubusercontent.com/3542623/196039744-8767085f-ddb7-4f17-994e-34d8429bdf31.gif)

Do you have any working aarch64 binary I can try out?


**Edit:** Added missing pictures

**Comment by AmrikSadhra** [comment]
Hey! Nice work :D The track fragment shader has moved on from when that port was made, so you'll have to transplant the precision modifiers over to the newer version [here](https://github.com/OpenNFS/OpenNFS/blob/main/shaders/TrackFragmentShader.frag). That should give you track rendering back. 

You'll get some hints from the terminal in which ONFS is running, the error output prints to stderr and not G3Log, hence won't appear on the on-screen log. Let me know if you want me to take a look at porting the shaders.

**Comment by myself600** [comment]
Well, I already did that in https://github.com/OpenNFS/OpenNFS/issues/32#issuecomment-1276594424. OpenNFS doesn't report any errors in terminal (see the attached log). So yeah, more changes are probably needed.

**Comment by myself600** [comment]
Hmm... it seems I wasn't clear enough so yes, I **do** need you @AmrikSadhra to "look at porting the shaders" since I don't know what else to do. Also @janisozaur and @ anyone if you can help making this ARM64 port possible.

**Comment by AmrikSadhra** [comment]
Understood, will take a look shortly 👍

**Comment by myself600** [comment]
Closing this as I'm now able to run NFS3 on ARM.
