### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by wa1one** [OpenNFS/OpenNFS#34]

**Comment by i-hate-compiling** [comment]
It aint, developer is busy with life tho, so you can say its on hold for now.

**Comment by ZippyZolton** [comment]
yes 😂

**Comment by AmrikSadhra** [comment]
There's still some occasional life on the dev branch! But yes, it's been hard finding the time to commit to this project outside of work.

**Comment by wa1one** [comment]
thank you all for the answers!
