### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by janisozaur** [OpenNFS/OpenNFS#8]
The reason (at least some of) your build CIs fail is because you're using the imgui-provided example headers, which are missing proper or any include guards at all. This causes a problem, because a forward-declaration of a function with a default argument can only appear once, even if the argument in question is the same. Without include guards in upstream headers, it would require workarounds in the client code.

Luckily, _someone_ just submitted a fix to imgui: https://github.com/ocornut/imgui/pull/2166, so whenever it gets accepted, please update the imgui submodule.

```
/home/janisozaur/workspace/OpenNFS/include/imgui/examples/imgui_impl_opengl3.h:30:79: error: default argument given for parameter 1 of ‘bool ImGui_ImplOpenGL3_Init(const char*)’ [-fpermissive]
 IMGUI_IMPL_API bool     ImGui_ImplOpenGL3_Init(const char* glsl_version = NULL);
                                                                               ^
In file included from /home/janisozaur/workspace/OpenNFS/src/RaceNet/../Renderer/RaceNetRenderer.h:14,
                 from /home/janisozaur/workspace/OpenNFS/src/RaceNet/TrainingGround.h:14,
                 from /home/janisozaur/workspace/OpenNFS/src/main.cpp:22:
/home/janisozaur/workspace/OpenNFS/include/imgui/examples/imgui_impl_opengl3.h:30:25: note: previous specification in ‘bool ImGui_ImplOpenGL3_Init(const char*)’ here
 IMGUI_IMPL_API bool     ImGui_ImplOpenGL3_Init(const char* glsl_version = NULL);
                         ^~~~~~~~~~~~~~~~~~~~~~
```

https://github.com/ocornut/imgui/blob/ed0f7004d02b39d69d9a658aac1aa270633923a8/examples/imgui_impl_opengl3.h#L30

I will post here once the PR in question is merged.

**Comment by janisozaur** [comment]
Upstream is fixed in https://github.com/ocornut/imgui/commit/2e6e1bec58d5b3c0fff59fd789311537abdf5f3e now.

**Comment by AmrikSadhra** [comment]
Thanks! Updated in 8673b29c25cba66d896066ea2ab50944b0e11850
